version: '3.7'

services:

  client:
    build: ./grpc/grpc_client/
    depends_on:
      - postgres
      - server
      # - cache
    volumes:
      - ./grpc/example.proto:/example.proto  
    ports:
      - "80:3000"
  
  # cache:
  #   image: bitnami/redis:6.0.16
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - ./cache/api/redis:/bitnami/redis/data
    # ports:
    #   - "6379:6379"

  server:
    build: ./grpc/grpc_server/
    depends_on:
      - postgres
    volumes:
      - ./grpc/example.proto:/example.proto

  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=Items
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=1234

#docker-compose up -d