version: '2'
services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    volumes:
      - /cassandra/init_cql:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      
  cassandra2:
    image: docker.io/bitnami/cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra3:
    image: docker.io/bitnami/cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  api:
    build: ./cassandra/
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/app/src